require_relative '../book'
require_relative '../classroom'
require_relative '../corrector'
require_relative '../person'
require_relative '../rental'
require_relative '../teacher'
require_relative '../student'
